AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: true
  UseAnonymousForwarding: false

Style/OpenStructUse:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit

Layout/LineLength:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false
