require 'eve_online/version'

require 'eve_online/exceptions/base'
require 'eve_online/exceptions/timeout_exception'
require 'eve_online/exceptions/unauthorized_exception'
require 'eve_online/exceptions/invalid_character_id_exception'

require 'eve_online/base'
require 'eve_online/base_xml'

require 'eve_online/blueprint'
require 'eve_online/bookmark'
require 'eve_online/bookmark_folder'
require 'eve_online/character'
require 'eve_online/event'
require 'eve_online/event_response_object'
require 'eve_online/implant'
require 'eve_online/skill'
require 'eve_online/jump_clone'
require 'eve_online/jump_clone_implant'
require 'eve_online/character_skills'
require 'eve_online/character_implants'
require 'eve_online/character_jump_clones'
require 'eve_online/character_jump_clone_implants'
require 'eve_online/standing'
require 'eve_online/contact_notification'
require 'eve_online/wallet_journal_entry'
require 'eve_online/market_order'

require 'eve_online/eve/character_id'

# XML API
require 'eve_online/xml/base'
require 'eve_online/xml/account_status'
require 'eve_online/xml/api_key_info'
require 'eve_online/xml/account_characters'
require 'eve_online/xml/character_account_balance'
require 'eve_online/xml/character_blueprints'
require 'eve_online/xml/character_bookmarks'
require 'eve_online/xml/character_sheet'
require 'eve_online/xml/character_medals'
require 'eve_online/xml/character_skill_queue'
require 'eve_online/xml/character_chat_channels'
require 'eve_online/xml/character_calendar_event_attendees'
require 'eve_online/xml/character_contact_list'
require 'eve_online/xml/character_contact_notifications'
require 'eve_online/xml/character_upcoming_calendar_events'
require 'eve_online/xml/character_skill_in_training'
require 'eve_online/xml/character_standings'
require 'eve_online/xml/character_contracts'
require 'eve_online/xml/character_contract_bids'
require 'eve_online/xml/character_contract_items'
require 'eve_online/xml/character_fac_war_stats'
require 'eve_online/xml/character_industry_jobs'
require 'eve_online/xml/character_industry_jobs_history'
require 'eve_online/xml/character_kill_mails'
require 'eve_online/xml/character_locations'
require 'eve_online/xml/character_mail_bodies'
require 'eve_online/xml/character_mailing_lists'
require 'eve_online/xml/character_mail_messages'
require 'eve_online/xml/character_market_orders'
require 'eve_online/xml/character_notifications'
require 'eve_online/xml/character_notification_texts'
require 'eve_online/xml/character_planetary_colonies'
require 'eve_online/xml/character_planetary_links'
require 'eve_online/xml/character_planetary_pins'
require 'eve_online/xml/character_planetary_routes'
require 'eve_online/xml/character_research'
require 'eve_online/xml/character_wallet_journal'
require 'eve_online/xml/character_wallet_transactions'

require 'eve_online/xml/corporation_market_orders'

require 'eve_online/xml/models/account_status'
require 'eve_online/xml/models/api_key_info'
require 'eve_online/xml/models/skill_queue_entry'
require 'eve_online/xml/models/account_type_object'

# ESI API
require 'eve_online/esi/base'

require 'eve_online/esi/character'
require 'eve_online/esi/character_portrait'
require 'eve_online/esi/character_skills'
require 'eve_online/esi/character_skill_queue'
require 'eve_online/esi/character_loyalty_points'
require 'eve_online/esi/character_wallet'
require 'eve_online/esi/character_assets'
require 'eve_online/esi/server_status'

require 'eve_online/esi/models/loyalty_point'
require 'eve_online/esi/models/skill_queue_entry'
require 'eve_online/esi/models/skill'
require 'eve_online/esi/models/asset'

# SDE
require 'eve_online/sde/base'

require 'eve_online/sde/agt_agent_types'
require 'eve_online/sde/agt_agents'
require 'eve_online/sde/agt_research_agents'
require 'eve_online/sde/races'
require 'eve_online/sde/inv_flags'
require 'eve_online/sde/inv_items'
require 'eve_online/sde/inv_names'
require 'eve_online/sde/inv_positions'

require 'eve_online/sde/models/agt_agent_type'
require 'eve_online/sde/models/agt_agent'
require 'eve_online/sde/models/agt_research_agent'
require 'eve_online/sde/models/race'
require 'eve_online/sde/models/inv_flag'
require 'eve_online/sde/models/inv_item'
require 'eve_online/sde/models/inv_name'
require 'eve_online/sde/models/inv_position'

module EveOnline
end
