name: "Markdown Lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

jobs:
  mdl:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: bewuethr/mdl-action@cd5146806e9938460327a2eed9238cc63a405af0 # v1.2.3
