name: "Markdown Lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

jobs:
  mdl:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: bewuethr/mdl-action@cd5146806e9938460327a2eed9238cc63a405af0 # v1.2.3
