name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.ruby_version == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0", "head"]
        activesupport: ["7.2", "8.0", "8.1", "main"]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/activesupport_${{ matrix.activesupport }}.gemfile

    name: Ruby ${{ matrix.ruby }} and ActiveSupport ${{ matrix.activesupport }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - name: Set up Ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler: latest
          bundler-cache: true
      - run: bundle exec rspec
      - run: bundle exec standardrb
